server:
  port: 8080
  servlet:
    session:
      # 设置默认的过期时间
      timeout: 1800
spring:
  application:
    # 启动时，应用的名称，可选
    name: reggie_take_out
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: 1229

  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.18.129:3306/reggie?characterEncoding=utf-8
        username: root
        password: qwe
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/reggie?characterEncoding=utf-8
        username: root
        password: 1229
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  # 允许bean定义覆盖
  main:
    allow-bean-definition-overriding: true



  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000 # 设置缓存数据的过期时间



#  配置静态资源访问路径
#  mvc:
#    static-path-pattern: "/backend/**"
#  web:
#    resources:
#      static-locations: [classpath:/backend/,classpath:/front/]
mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID


# 指定上传文件位置
reggie:
  path: D:\programTools\Java\workspace\AtguiguProject\reggie\src\main\resources\images\
